### ISSUE TITLE
初始化后管理员权限怎么没了？

### ISSUE THREAD

**Issue by laosandegudai** [zhang8043/abp-react-antd#1]
初始化后管理员权限怎么没了？
看了getall,grantpermission木有值。

**Comment by laosandegudai** [comment]
个人中心差几个字就一个学校了。
问题找到了，登陆后需要改密码，木有跳转到修改密码页面。

**Comment by zhang8043** [comment]
最近因工作比较忙，还未添加登陆修改密码页面，会尽快完善该框架。谢谢支持

**Comment by laosandegudai** [comment]
为什么打包出来没合并这么多文件啊？
![a6o kj 6 x 1rz a a5 gk](https://user-images.githubusercontent.com/17979159/51813635-3f3e7a80-22f2-11e9-9e06-7d80cc9afabe.png)

**Comment by zhang8043** [comment]
ant design pro 默认是按路由分模块打包的
