### ISSUE TITLE
后端建议基于ABP vNext版本来开发

### ISSUE THREAD

**Issue by liaoyongxiong** [zhang8043/abp-react-antd#2]
ABP vNext是 APB的下一代产品( https://cn.abp.io/blog/Abp/Abp-vNext-Announcement )，根据官方的计划，5、6月份会出1.0版本。
代码实现上，ABP vNext充分利用了Net Core基础架构带来的便利，支持微服务。

**Comment by jackzhum** [comment]
事实上我也有打算等vNext版本出正式版后，把一些常用的服务建个微服务架构。
比如：微信，短信，快递，工作流，全搬上去。弄一个服务平台。

**Comment by zhang8043** [comment]
主要现在vNext相关的资料太少，做起来有一些吃力。

**Comment by mxu9** [comment]
关于abp vnext有新的进展吗？

**Comment by jackzhum** [comment]
> 关于abp vnext有新的进展吗？

https://abp.io
