### ISSUE TITLE
请问初始账号和密码是什么？

### ISSUE THREAD

**Issue by huaxiaosxl** [zhang8043/abp-react-antd#3]
我用admin / ant.design登录提示密码不正确，请告诉我正确的登录账号和密码，谢谢！

**Comment by zhang8043** [comment]
初始账户为：admin 密码为：123qwe，如登录失败请查看用户表中用户是否锁定。

**Comment by huaxiaosxl** [comment]
谢谢！
用您提供的这个账号和密码不再提示账号或密码错误，但点击登录后也没有任何响应了。哪个字段用来检查用户是否锁定？

**Comment by zhang8043** [comment]
AbpUsers表中  IsLockoutEnabled 是否锁定 ，ShouldChangePasswordOnNextLogin  下次登录修改密码

**Comment by zhang8043** [comment]
下次更新添加数据验证和其他功能。

**Comment by huaxiaosxl** [comment]
把这两个字段的值都改成False后登录没有问题了，非常感谢！
